### ISSUE TITLE
TikTok TTS mode non-functional

### ISSUE THREAD

**Issue by Mudb0y** [Discord-TTS/Bot#82]
The TikTok TTS mode appears not to work. Whenever text is typed, nothing is spoken-back. This might be due to API changes in the TikTok API as other tools I've used that utilised the TikTok TTS voices have broke around late august.

**Comment by GnomedDev** [comment]
Yeah, tiktok locked down the API to require authentication, which allows them to easily ban automated uses. I'm working on removing it but due to dependency updates it will take a while.

**Comment by GnomedDev** [comment]
I've removed the mode from the mode selector, I'll think about resetting people's modes who have it set to tiktok however due to the possibility of it being usable again in the future I'm leaving their modes as is for now.
